application:
  debug: True 
  host: 'localhost' 
  port: 64088

log_setting:
  loglevel: 1  #1=DEBUG, 2=ERROR         DEBUG > ERROR
  log_to_console: True
  logpath: 'D:\\Downloads\\git_projects\\commonlearning\\TMDB-Movie-Recommender-System\\'